# Generated by Django 6.0.5 on 2026-07-04 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_alter_replyvote_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='discussionbookmark',
            index=models.Index(fields=['user', 'created_at'], name='game_discus_user_id_3d456a_idx'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['user', 'created_at'], name='game_reply_user_id_7ec97d_idx'),
        ),
    ]
