# Generated by Django 6.0.6 on 2026-07-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0034_discussionbookmark_game_discus_user_id_3d456a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='day_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='last_played_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
