# Generated by Django 6.0.6 on 2026-07-13 06:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0035_userprogress_day_streak_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activegame',
            name='game_active_status_22ef23_idx',
        ),
        migrations.RenameField(
            model_name='activegame',
            old_name='last_active',
            new_name='last_activity_at',
        ),
        migrations.AddField(
            model_name='activegame',
            name='game_state',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activegame',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='activegame',
            index=models.Index(fields=['status', 'last_activity_at'], name='game_active_status_564cc7_idx'),
        ),
    ]
