# Generated by Django 6.0.6 on 2026-07-13 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0036_remove_activegame_game_active_status_22ef23_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='activegame',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active'), ('user__isnull', False)), fields=('user',), name='unique_active_game_per_user'),
        ),
        migrations.AddConstraint(
            model_name='activegame',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 0)), name='activegame_version_gte_0'),
        ),
    ]
