# Generated by Django 6.0.6 on 2026-07-13 09:33

import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0037_activegame_unique_active_game_per_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activegame',
            name='game_state',
            field=models.JSONField(blank=True, null=True, validators=[game.models.validate_game_state]),
        ),
    ]
